

  Running 'PP load (plain)' :
    repeat #1 ..     time #0 :     1.214632 ...
    time #1 :     1.202498 ...
    time #2 :     1.198307 ...
  TOOK     1.205146 ...
    repeat #2 ..     time #0 :     1.201980 ...
    time #1 :     1.200440 ...
    time #2 :     1.202561 ...
  TOOK     1.201660 ...
    repeat #3 ..     time #0 :     1.198982 ...
    time #1 :     1.201798 ...
    time #2 :     1.199083 ...
  TOOK     1.199954 ...


Test                        "PP load (plain)" :     1.199954 seconds



  Running 'PP load (structured)' :
    repeat #1 ..     time #0 :     0.916236 ...
    time #1 :     0.891232 ...
    time #2 :     0.920908 ...
    time #3 :     0.892366 ...
  TOOK     0.905185 ...
    repeat #2 ..     time #0 :     0.919429 ...
    time #1 :     0.892041 ...
    time #2 :     0.918154 ...
    time #3 :     0.893540 ...
  TOOK     0.905791 ...
    repeat #3 ..     time #0 :     0.917932 ...
    time #1 :     0.919616 ...
    time #2 :     0.891692 ...
    time #3 :     0.918935 ...
  TOOK     0.912044 ...


Test                   "PP load (structured)" :     0.912044 seconds



  Running 'PP data load' :
    repeat #1 ..     time #0 :     0.571665 ...
    time #1 :     0.553487 ...
    time #2 :     0.544576 ...
    time #3 :     0.519451 ...
  TOOK     0.547295 ...
    repeat #2 ..     time #0 :     0.529220 ...
    time #1 :     0.555426 ...
    time #2 :     0.532910 ...
    time #3 :     0.549919 ...
  TOOK     0.541869 ...
    repeat #3 ..     time #0 :     0.547964 ...
    time #1 :     0.566212 ...
    time #2 :     0.522966 ...
    time #3 :     0.559388 ...
  TOOK     0.549133 ...
    repeat #4 ..     time #0 :     0.525897 ...
    time #1 :     0.527768 ...
    time #2 :     0.549140 ...
    time #3 :     0.528121 ...
  TOOK     0.532732 ...


Test                           "PP data load" :     0.532732 seconds



  Running 'Fieldsfile load (plain)' :
    repeat #1 .. /home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/rules.py:334: UserWarning: Unable to create instance of HybridHeightFactory. The source data contains no field(s) for 'orography'.
  warnings.warn(msg.format(factory=factory_name))
  TOOK     5.674174 ...
    repeat #2 ..   TOOK     5.613587 ...
    repeat #3 ..   TOOK     5.888512 ...


Test                "Fieldsfile load (plain)" :     5.888512 seconds



  Running 'Fieldsfile load (structured)' :
    repeat #1 ..   TOOK     2.623897 ...
    repeat #2 ..   TOOK     2.589784 ...
    repeat #3 ..   TOOK     2.619734 ...


Test           "Fieldsfile load (structured)" :     2.619734 seconds



  Running 'Fieldsfile data load' :
    repeat #1 ..     time #0 :     0.394938 ...
    time #1 :     0.448937 ...
    time #2 :     0.433252 ...
    time #3 :     0.713258 ...
  TOOK     0.497596 ...
    repeat #2 ..     time #0 :     0.400650 ...
    time #1 :     0.645149 ...
    time #2 :     0.391479 ...
    time #3 :     0.569193 ...
  TOOK     0.501618 ...
    repeat #3 ..     time #0 :     0.431787 ...
    time #1 :     0.468989 ...
    time #2 :     0.456224 ...
    time #3 :     0.434188 ...
  TOOK     0.447797 ...
    repeat #4 ..     time #0 :     0.405796 ...
    time #1 :     0.613401 ...
    time #2 :     0.452646 ...
    time #3 :     0.407150 ...
  TOOK     0.469748 ...


Test                   "Fieldsfile data load" :     0.469748 seconds



  Running 'Fieldsfile mean calc' :
    repeat #1 .. /home/h05/itpp/git/iris/iris_main/lib/iris/coords.py:1191: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'time'.
  warnings.warn(msg.format(self.name()))
/home/h05/itpp/git/iris/iris_main/lib/iris/coords.py:1191: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'pressure'.
  warnings.warn(msg.format(self.name()))
/home/h05/itpp/git/iris/iris_main/lib/iris/coords.py:1191: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'forecast_period'.
  warnings.warn(msg.format(self.name()))
    time #0 :     1.100210 ...
    time #1 :     1.157519 ...
    time #2 :     1.118991 ...
    time #3 :     1.057666 ...
    time #4 :     1.045186 ...
  TOOK     1.095914 ...
    repeat #2 ..     time #0 :     1.061410 ...
    time #1 :     1.049747 ...
    time #2 :     1.007330 ...
    time #3 :     1.003069 ...
    time #4 :     1.028903 ...
  TOOK     1.030092 ...
    repeat #3 ..     time #0 :     1.051154 ...
    time #1 :     1.024224 ...
    time #2 :     1.045346 ...
    time #3 :     1.054455 ...
    time #4 :     1.045657 ...
  TOOK     1.044167 ...


Test                   "Fieldsfile mean calc" :     1.044167 seconds



  Running 'NetCDF load (plain)' :
    repeat #1 .. /home/h05/itpp/git/iris/iris_main/lib/iris/fileformats/cf.py:798: UserWarning: Missing CF-netCDF measure variable u'areacella', referenced by netCDF variable u'tas'
  warnings.warn(message % (variable_name, nc_var_name))
    time #0 :     0.327555 ...
    time #1 :     0.259858 ...
    time #2 :     0.248733 ...
    time #3 :     0.245022 ...
  TOOK     0.270292 ...
    repeat #2 ..     time #0 :     0.245375 ...
    time #1 :     0.245195 ...
    time #2 :     0.245411 ...
    time #3 :     0.245741 ...
  TOOK     0.245430 ...
    repeat #3 ..     time #0 :     0.246974 ...
    time #1 :     0.251685 ...
    time #2 :     0.246319 ...
    time #3 :     0.245704 ...
  TOOK     0.247670 ...
    repeat #4 ..     time #0 :     0.245406 ...
    time #1 :     0.245588 ...
    time #2 :     0.245662 ...
    time #3 :     0.245055 ...
  TOOK     0.245428 ...


Test                    "NetCDF load (plain)" :     0.245428 seconds



  Running 'NetCDF data load' :
    repeat #1 ..   TOOK     1.285787 ...
    repeat #2 ..   TOOK     1.260392 ...
    repeat #3 ..   TOOK     1.257273 ...
    repeat #4 ..   TOOK     1.377910 ...


Test                       "NetCDF data load" :     1.377910 seconds



  Running 'NetCDF mean calc' :
    repeat #1 ..     time #0 :     1.084295 ...
    time #1 :     0.963851 ...
    time #2 :     1.004635 ...
    time #3 :     1.002018 ...
    time #4 :     1.046168 ...
  TOOK     1.020193 ...
    repeat #2 ..     time #0 :     1.132080 ...
    time #1 :     1.097921 ...
    time #2 :     0.975590 ...
    time #3 :     0.975906 ...
    time #4 :     1.019018 ...
  TOOK     1.040103 ...
    repeat #3 ..     time #0 :     1.031977 ...
    time #1 :     1.004175 ...
    time #2 :     1.044482 ...
    time #3 :     0.855783 ...
    time #4 :     1.052981 ...
  TOOK     0.997880 ...


Test                       "NetCDF mean calc" :     0.997880 seconds



  Running 'PP save to PP' :
    repeat #1 ..   TOOK     3.345545 ...
    repeat #2 ..   TOOK     3.279808 ...
    repeat #3 ..   TOOK     3.146187 ...


Test                          "PP save to PP" :     3.146187 seconds



  Running 'PP save to NetCDF' :
    repeat #1 ..   TOOK     1.142406 ...
    repeat #2 ..   TOOK     1.177972 ...
    repeat #3 ..   TOOK     1.142585 ...


Test                      "PP save to NetCDF" :     1.142585 seconds



  Running 'NetCDF save to NetCDF' :
    repeat #1 ..   TOOK     1.353740 ...
    repeat #2 ..   TOOK     1.407783 ...
    repeat #3 ..   TOOK     1.240710 ...
Traceback (most recent call last):
  File "standard_performance_tests.py", line 206, in <module>
    run_tests()
  File "standard_performance_tests.py", line 196, in run_tests
    do_save, [nc_save_cube, 'tmp.nc'])
  File "standard_performance_tests.py", line 117, in exercise
    atol=abstol, rtol=reltol)
  File "/data/local/itpp/miniconda/envs/dask_speedchecks/lib/python2.7/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/data/local/itpp/miniconda/envs/dask_speedchecks/lib/python2.7/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.08, atol=0.001

(mismatch 100.0%)
 x: array(1.407783)
 y: array(1.24071)
